### ISSUE TITLE
Certaines actions bloquent le fenêtre web

### ISSUE THREAD

**Issue by sctfic** [Coaxis-ASP/opt#10]
Certaines actions laissent un "gray shadow layer" devant et plus aucune actions n'est possibles :

```
.modal-backdrop {
    position: fixed;
    z-index: 1040;
    background-color: #000;
}
```

**Comment by edouard-lopez** [comment]
J'ai le cas quand je supprime un `site` ou une `imprimante`, ça devrait être rapide à corriger
