### ISSUE TITLE
Modifier le délai entre les appels api/réseau

### ISSUE THREAD

**Issue by sctfic** [Coaxis-ASP/opt#11]
Pour les gros clients avec plus de 100 imprimantes les serveurs passent leur temps à faire des `ping` et `telnet` il faudrait les espacer de plus de 15s.

Par exemple, proportionnel au nombre de noeuds…

    10sec + ([int]NbNode/5)

> 3imps = 10sec
> 30imps = 16sec
> 150imps = 40sec

**Comment by edouard-lopez** [comment]
fixed by 3772939af5.

### Todo

grouper avec #33 

* [x] create new git tag `v1.10.0`
* [ ] release new docker image 

      cd coaxisopt/
      ./deploy.sh v1.10.0

**Comment by edouard-lopez** [comment]
:information_source: J'affiche le délai entre les requêtes dans via un `console.info()`.
