### ISSUE TITLE
Creation d'imprimante avec un port spécifique

### ISSUE THREAD

**Issue by sctfic** [Coaxis-ASP/opt#13]
**related:** #31, #19,  [daemon/makefile:add-channel](https://github.com/Coaxis-ASP/opt/blob/master/daemon/makefile#L158-L196), 

Todo:
* [x] write tests to support `port` field ;
* [x] implement support ;

---

l'API doit pouvoir créer une imprimante avec un port spécifique.
ceci afin de permettre de restaurer des imprimantes.
par exemple après un export via l'API

j'ai déjà des export périodique avec le re-import possible, mais les ports change tous a ce moment la !
donc la comptable imprime les fiche de paie a l'accueil !!!
ou pire dans le cas de conteneur mutualisé pour plusieurs client !

**Comment by sctfic** [comment]
exemple d'export.

    [
    {
        "channels":  [
                         {
                             "id":  0,
                             "description":  "LATESTE Imp",
                             "hostname":  "10.200.7.171",
                             "ports":  {
                                           "send":  9100,
                                           "forward":  "remote",
                                           "listen":  9118
                                       }
                         }
                     ],
        "id":  "lateste",
        "hostname":  "10.200.7.184"
    },
    {
        "channels":  [
                         {
                             "id":  1,
                             "description":  "LIM KONICA RDC",
                             "hostname":  "10.200.8.112",
                             "ports":  {
                                           "send":  9100,
                                           "forward":  "remote",
                                           "listen":  9109
                                       }
                         },
                         {
                             "id":  3,
                             "description":  "LIM REX 1ER",
                             "hostname":  "10.200.8.115",
                             "ports":  {
                                           "send":  9100,
                                           "forward":  "remote",
                                           "listen":  9110
                                       }
                         },
                         {
                             "id":  4,
                             "description":  "LIM KONIKA ETAGE",
                             "hostname":  "10.200.8.114",
                             "ports":  {
                                           "send":  9100,
                                           "forward":  "remote",
                                           "listen":  9108
                                       }
                         }
                     ],
        "id":  "limoges",
        "hostname":  "10.200.8.121"
    },

**Comment by sctfic** [comment]
j'ai re-importer 146 imprimantes a la main, grosse galere !

**Comment by edouard-lopez** [comment]
Tu arrives à ajouter des imprimantes par lot ? 

J'ai l'impression d'avoir une incohérence entre les données envoyées par le front (`description`, `hostname`, `port`) et ce qu'attends l'API (`site`, `hostname`, `description`)

Frontend 

https://github.com/Coaxis-ASP/opt/blob/30bbf60d56a946fb4f5b3d3dbe8855102a3387b4/daemon/frontend/src/services/printers.service.js#L7-L9

API
https://github.com/Coaxis-ASP/opt/blob/30bbf60d56a946fb4f5b3d3dbe8855102a3387b4/daemon/api/views.py#L107-L109

**Comment by edouard-lopez** [comment]
OK, le `port` n'est ni gérer au niveau de l'API, ni au niveau du makefile:

https://github.com/Coaxis-ASP/opt/blob/30bbf60d56a946fb4f5b3d3dbe8855102a3387b4/daemon/makefile#L154-L158

Le point positif c'est qu'on a des [tests pour la tâche `add-channel`](https://github.com/Coaxis-ASP/opt/blob/master/daemon/test/add-channel.tests.bats), donc le refacto sera beaucoup moins risqué!

**Comment by sctfic** [comment]
si tu préfère faire direct en Python j’approuve direct, le makefile c'est galère ! a mon sens on y touche plus et on travaille sur le python uniquement

**Comment by edouard-lopez** [comment]
Ré-écrire le module en Python c'est une charge de travail plus importante, avec une complexité plus élevée et sans apporter aucune valeur au produit final.

Dans un premier temps on va extraire le `bash` du fichier `makefile`, ça nous permet d'introduire du découplage, améliorant la maintenabilité et ouvrir à une future ré-écriture en Python.

**Comment by edouard-lopez** [comment]
Résolu en Python au final
