### ISSUE TITLE
Permettre de modifier la limite d'Upload/Download via API

### ISSUE THREAD

**Issue by sctfic** [Coaxis-ASP/opt#15]
**related:** #12 

Permettre de changer la conf de débit dans `/etc/mast/sites` au moins `UploadLimit`

    declare -i UploadLimit="100"

Nous avons besoin d'un endpoint API permettant de lire/écrire la valeur de l'upload/download. 

Dans un second temps on permettra la modification via l'interface, avec des valeurs prédéfinis : `100,150,200,300,400,500,750` (et les multiples `/10` ou `*10`)

**Comment by sctfic** [comment]
je me débrouille pour l'interface, pas besoin de modifier la page web

**Comment by sctfic** [comment]
Exemple de cas :
- le client a une liaison 20Mb/s en nominal et bascule sur le secour 4Mo/sec => on baisse la vitesse temporairement
- le client passe d'une laison  SDSL 2Mo/s a une Fibre 50Mo/sec => on aumente la vitesse

**Comment by edouard-lopez** [comment]
Excellent, je n'avais pas du tout ce niveau de criticité en tête !

**Comment by edouard-lopez** [comment]
closed by #24
